import "./globals.css";
import type { Metadata } from "next";
import RecoilProvider from "./recoilProvider";
import { NextScript } from "next/document";

export const metadata: Metadata = {
  title: "Trello 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilProvider>
        <body className="bg-[#F5F6F8]">{children}</body>
      </RecoilProvider>
    </html>
  );
}
